//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cita
    {
        public int ID { get; set; }
        public string ID_Médico { get; set; }
        public int Cédula_Paciente { get; set; }
        public System.DateTime Hora_Cita { get; set; }
        public string Tipo_Servicio { get; set; }
        public string Diagnóstico { get; set; }
        public string Tratamiento { get; set; }
    
        public virtual Paciente Paciente { get; set; }
        public virtual Médico Médico { get; set; }
    }
}
