//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clínica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clínica()
        {
            this.Clínica_Médico = new HashSet<Clínica_Médico>();
            this.Clínica_Paciente = new HashSet<Clínica_Paciente>();
        }
    
        public string ID { get; set; }
        public string Nombre { get; set; }
        public string Dirección { get; set; }
        public Nullable<int> Teléfono { get; set; }
        public string Correo { get; set; }
        public string Sitio_Web { get; set; }
        public string Horario { get; set; }
        public string Provincia { get; set; }
        public string Cantón { get; set; }
        public string Distrito { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clínica_Médico> Clínica_Médico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clínica_Paciente> Clínica_Paciente { get; set; }
    }
}
