//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clínica_Médico
    {
        public int ID { get; set; }
        public string ID_Clínica { get; set; }
        public string ID_Médico { get; set; }
    
        public virtual Clínica Clínica { get; set; }
        public virtual Médico Médico { get; set; }
    }
}
