//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente_Medico
    {
        public int CedulaPaciente { get; set; }
        public int CedulaMedico { get; set; }
        public int ID { get; set; }
    
        public virtual Paciente Paciente { get; set; }
    }
}
